language: python
sudo: false

python:
  - 3.5
  - 3.4
  - 2.7
  
install:
 - pip install unittest2
 - pip install nose
 - pip install pyxb
 - pip install lxml

before_script:
  - git submodule update --remote --recursive

script:
 - nosetests
 - python setup.py install
 - cd sample-code-python
 - python ./test-runner.py
