language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
 - pip install unittest2
 - pip install nose
 - pip install pyxb
script: nosetests
