language: python
sudo: false

python:
  - "2.7"
  - "pypy"

install:
 - pip install unittest2
 - pip install nose
 - pip install pyxb
 - pip install coveralls
script: nosetests

after_success:
  - coveralls
