language: python
sudo: false

python:
  - "2.7"
  - "pypy"

install:
 - pip install unittest2
 - pip install nose
 - pip install pyxb

before_script:
  - git submodule update --remote --recursive

script: nosetests
