language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  # - "pypy" Disabling pypy until travis moves to newer version, known issue with lxml crashing pypy
  
install:
 - pip install unittest2
 - pip install nose
 - pip install pyxb
 - pip install lxml
 - pip install coveralls

before_script:
  - git submodule update --remote --recursive

script:
 - nosetests --with-coverage -cover-package=authorizenet
 - coveralls
 - python setup.py install
 - cd sample-code-python
 - python ./test-runner.py
